/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopecas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.Timer;

/**
 *
 * @author nicol
 */
public class CadastroAgenda extends javax.swing.JFrame {

    private AgendaDAO agendaDAO;

    static void abrir() {
        CadastroAgenda frame = new CadastroAgenda();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* capturando o tamanho da tela onde está rodando este programa */
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((tela.width - frame.getSize().width) / 2,
                (tela.height - frame.getSize().height) / 2);
        frame.setVisible(true);
    }

    /**
     * Creates new form CadastroAgenda
     */
    public CadastroAgenda() {
        initComponents();
        agendaDAO = new AgendaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ftCodigo = new javax.swing.JTextField();
        ftHoraServico = new javax.swing.JFormattedTextField();
        ftDataServico = new javax.swing.JFormattedTextField();
        ftDataAgendada = new javax.swing.JTextField();
        ftHoraAgendada = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfCodigoCliente = new javax.swing.JTextField();
        tfCodigoVeiculo = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAgenda = new javax.swing.JTable();
        btNovo = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 20)); // NOI18N
        jLabel1.setText("Cadastro de Agendamentos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações de Agendamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Código do Agendamento:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Hora do Serviço:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Data do Serviço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Data do Agendamento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Hora do Agendamento:");

        ftCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftCodigoActionPerformed(evt);
            }
        });

        try {
            ftHoraServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftDataServico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Pesquisar.jpg"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Placa do Veículo:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Código do Cliente:");

        try {
            tfCodigoVeiculo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btBuscar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ftDataServico))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ftHoraServico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ftDataAgendada)
                                .addComponent(ftHoraAgendada, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfCodigoVeiculo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftHoraServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ftDataAgendada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftDataServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ftHoraAgendada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tfCodigoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jtAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAgendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAgenda);

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Novo.jpg"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btGravar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Gravar.jpg"))); // NOI18N
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Atualizar.jpg"))); // NOI18N
        btEditar.setText("Atualizar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Excluir.jpg"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Limpar.jpg"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/voltar.jpg"))); // NOI18N
        btSair.setText("Voltar");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(142, 142, 142)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(75, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        FormPrincipal.abrir();
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        Timer timer = new Timer(1000, new CadastroAgenda.timer());
        timer.stop();
        if (ftCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o código do agendamento");

            if (!ftCodigo.getText().equals("")) {
                agendaDAO.agenda.setCodigoAgendada(ftCodigo.getText());
                if (agendaDAO.localizarAgendamento()) {
                    ftCodigo.setText(agendaDAO.agenda.getCodigoAgendada());
                    ftHoraServico.setText(agendaDAO.agenda.getHoraServico());
                    ftDataServico.setText(agendaDAO.agenda.getDataServico());
                    ftDataAgendada.setText(agendaDAO.agenda.getDataAgendada());
                    ftHoraAgendada.setText(agendaDAO.agenda.getHoraAgendada());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado");
            atualizaCampos();
        }


    }//GEN-LAST:event_btBuscarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        String codigoNovo;
        limpaCamposNovo(false, false);
        codigoNovo = "" + agendaDAO.proximoAgendamento();
        if (!codigoNovo.equals("0")) {
            ftCodigo.setText(codigoNovo);
        }
        ftHoraServico.requestFocus();
        Timer timer = new Timer(1000, new CadastroAgenda.timer());
        timer.start();
        campoDesa(false);
    }//GEN-LAST:event_btNovoActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        if (ftCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código.");
            ftCodigo.requestFocus();
            return;
        }
        if (ftHoraServico.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Hora do Serviço.");
            ftHoraServico.requestFocus();
            return;
        }
        if (ftDataServico.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Data do Serviço.");
            ftDataServico.requestFocus();
            return;
        }
        if (ftDataAgendada.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Data do Agendamento.");
            ftDataAgendada.requestFocus();
            return;
        }
        if (ftHoraAgendada.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Hora do Agendamento.");
            ftHoraAgendada.requestFocus();
            return;
        }
        if (tfCodigoVeiculo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código do Veiculo.");
            tfCodigoVeiculo.requestFocus();
            return;
        }
        if (tfCodigoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código do Cliente.");
            tfCodigoCliente.requestFocus();
            return;
        }
        agendaDAO.agenda.setCodigoAgendada(ftCodigo.getText());
        agendaDAO.agenda.setHoraServico(ftHoraServico.getText());
        String dataEN = FormatDateEN(ftDataServico.getText());
        agendaDAO.agenda.setDataServico(dataEN);
        String dataEN2 = FormatDateEN(ftDataAgendada.getText());
        agendaDAO.agenda.setDataAgendada(dataEN2);
        agendaDAO.agenda.setHoraAgendada(ftHoraAgendada.getText());
        agendaDAO.agenda.setFkCarro(tfCodigoVeiculo.getText());
        agendaDAO.agenda.setFkCliente(tfCodigoCliente.getText());
        JOptionPane.showMessageDialog(null, agendaDAO.inserirAgendamento());
    }//GEN-LAST:event_btGravarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        if (ftCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código.");
            ftCodigo.requestFocus();
            return;
        }
        if (ftHoraServico.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Hora do Serviço.");
            ftHoraServico.requestFocus();
            return;
        }
        if (ftDataServico.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Data do Serviço.");
            ftDataServico.requestFocus();
            return;
        }
        if (ftDataAgendada.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Data do Agendamento.");
            ftDataAgendada.requestFocus();
            return;
        }
        if (ftHoraAgendada.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Hora do Agendamento.");
            ftHoraAgendada.requestFocus();
            return;
        }
        agendaDAO.agenda.setCodigoAgendada(ftCodigo.getText());
        agendaDAO.agenda.setHoraServico(ftHoraServico.getText());
        String dataEN = FormatDateEN(ftDataServico.getText());
        agendaDAO.agenda.setDataServico(dataEN);
        String dataEN2 = FormatDateEN(ftDataAgendada.getText());
        agendaDAO.agenda.setDataAgendada(dataEN2);
        agendaDAO.agenda.setHoraAgendada(ftHoraAgendada.getText());
        agendaDAO.agenda.setFkCarro(tfCodigoVeiculo.getText());
        agendaDAO.agenda.setFkCliente(tfCodigoCliente.getText());
        JOptionPane.showMessageDialog(null, agendaDAO.atualizarAgenda());
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (ftCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o código do agendamento a ser excluído.");
            ftCodigo.requestFocus();
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja Excluir?", "ALERTA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == 0) {
            agendaDAO.agenda.setCodigoAgendada("" + ftCodigo.getText());
            JOptionPane.showMessageDialog(null, agendaDAO.excluirAgendamento());
            limpaCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Carro não excluido.");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String sql = "select * from agenda";
        preencherTabela(sql);
        Date dataSistema = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        ftDataAgendada.setText(formato.format(dataSistema));
        //Hora
        camposTela(false, false);
    }//GEN-LAST:event_formWindowActivated

    private void jtAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAgendaMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jtAgenda.getSelectedRow();
        if (linhaSelecionada >= 0) {
            ftCodigo.setText(jtAgenda.getValueAt(linhaSelecionada, 0).toString());
            ftHoraServico.setText(jtAgenda.getValueAt(linhaSelecionada, 1).toString());
            ftDataServico.setText(jtAgenda.getValueAt(linhaSelecionada, 2).toString());
            ftDataAgendada.setText(jtAgenda.getValueAt(linhaSelecionada, 3).toString());
            ftHoraAgendada.setText(jtAgenda.getValueAt(linhaSelecionada, 4).toString());
            tfCodigoVeiculo.setText(jtAgenda.getValueAt(linhaSelecionada, 5).toString());
            tfCodigoCliente.setText(jtAgenda.getValueAt(linhaSelecionada, 6).toString());
        }
    }//GEN-LAST:event_jtAgendaMouseClicked

    private void ftCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftCodigoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAgenda().setVisible(true);
            }
        });
    }

    private void limpaCampos() {
        ftCodigo.setText("");
        ftHoraServico.setText("");
        ftDataServico.setText("");
        tfCodigoVeiculo.setText("");
        tfCodigoCliente.setText("");
    }

    public String FormatDateBR(String dataEN) {
        String dataBR = dataEN;
        dataBR = dataBR.substring(8, 10) + "/"
                + dataBR.substring(5, 7) + "/"
                + dataBR.substring(0, 4);
        return dataBR;
    }

    //Formantando do padrão 'BRASILEIRO' para o padrão 'AMERICANO'
    public String FormatDateEN(String dataBR) {
        String dataEN = dataBR;
        dataEN = dataEN.substring(6, 10) + "/"
                + dataEN.substring(3, 5) + "/"
                + dataEN.substring(0, 2);
        return dataEN;
    }

    public void camposTela(boolean tHoraAgenda, boolean tDataAgenda) {
        ftDataAgendada.setEnabled(tDataAgenda);
        ftHoraAgendada.setEnabled(tHoraAgenda);
    }

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"CÓDIGO", "HORA DO SERVIÇO", "DATA DO SERVIÇO", "DATA DO AGENDAMENTO", "HORA DO AGENDAMENTO", "Código Veículo", "Código Cliente"};
        agendaDAO.pesquisarAgenda(sql);
        try {
            agendaDAO.resultSet.first();
            do {
                dados.add(new Object[]{
                    agendaDAO.resultSet.getString("codigoAgendada"),
                    agendaDAO.resultSet.getString("horaServico"),
                    agendaDAO.resultSet.getString("dataServico"),
                    agendaDAO.resultSet.getString("dataAgendada"),
                    agendaDAO.resultSet.getString("horaAgendada"),
                    agendaDAO.resultSet.getString("fkCarro"),
                    agendaDAO.resultSet.getString("fkCliente"),});
            } while (agendaDAO.resultSet.next());
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro: \n" + erro);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jtAgenda.setModel(modelo);
        jtAgenda.getColumnModel().getColumn(0).setPreferredWidth(80);
        jtAgenda.getColumnModel().getColumn(0).setResizable(false);
        jtAgenda.getColumnModel().getColumn(1).setPreferredWidth(100);
        jtAgenda.getColumnModel().getColumn(1).setResizable(true);
        jtAgenda.getColumnModel().getColumn(2).setPreferredWidth(100);
        jtAgenda.getColumnModel().getColumn(2).setResizable(false);
        jtAgenda.getColumnModel().getColumn(3).setPreferredWidth(100);
        jtAgenda.getColumnModel().getColumn(3).setResizable(false);
        jtAgenda.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtAgenda.getColumnModel().getColumn(4).setResizable(false);
        jtAgenda.getColumnModel().getColumn(5).setPreferredWidth(100);
        jtAgenda.getColumnModel().getColumn(5).setResizable(false);
        jtAgenda.getColumnModel().getColumn(6).setPreferredWidth(100);
        jtAgenda.getColumnModel().getColumn(6).setResizable(false);
        jtAgenda.getTableHeader().setReorderingAllowed(false);
        jtAgenda.setAutoResizeMode(jtAgenda.AUTO_RESIZE_OFF);
        jtAgenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        agendaDAO.conecta.fecharBD();
    }

    class timer implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            ftHoraAgendada.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

    public void campoDesa(boolean cCgodio) {
        ftCodigo.setEnabled(cCgodio);
    }

    public void limpaCamposNovo(boolean data, boolean hora) {
        ftDataServico.setText("");
        ftHoraServico.setText("");
    }

    public void atualizaCampos() {
        agendaDAO.agenda.setCodigoAgendada(ftCodigo.getText());
        if (agendaDAO.localizarAgendamento()) {
            ftCodigo.setText(agendaDAO.agenda.getCodigoAgendada());
            ftHoraServico.setText(agendaDAO.agenda.getHoraServico());
            ftDataServico.setText(agendaDAO.agenda.getDataServico());
            ftDataAgendada.setText(agendaDAO.agenda.getDataAgendada());
            ftHoraAgendada.setText(agendaDAO.agenda.getHoraAgendada());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField ftCodigo;
    private javax.swing.JTextField ftDataAgendada;
    private javax.swing.JFormattedTextField ftDataServico;
    private javax.swing.JTextField ftHoraAgendada;
    private javax.swing.JFormattedTextField ftHoraServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtAgenda;
    private javax.swing.JTextField tfCodigoCliente;
    private javax.swing.JFormattedTextField tfCodigoVeiculo;
    // End of variables declaration//GEN-END:variables

}
