package autopecas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import autopecas.ValidarCPF;

public class CadastroCliente extends javax.swing.JFrame {

    private ClienteDAO clienteDAO;
    ConectaBD conecta = new ConectaBD();
    int a;
    int b;

    static void abrir() {
        CadastroCliente frame = new CadastroCliente();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* capturando o tamanho da tela onde está rodando este programa */
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((tela.width - frame.getSize().width) / 2,
                (tela.height - frame.getSize().height) / 2);
        frame.setVisible(true);
    }

    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        clienteDAO = new ClienteDAO();
        conecta.conectarBD();
        setTitle("Sistema de Cadastro de Cliente- Elite Auto-Car");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jPasswordField1 = new javax.swing.JPasswordField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        ftCpf = new javax.swing.JFormattedTextField();
        ftTelefone = new javax.swing.JFormattedTextField();
        ftCelular = new javax.swing.JFormattedTextField();
        btBuscar = new javax.swing.JButton();
        rbMasc = new javax.swing.JRadioButton();
        rbFem = new javax.swing.JRadioButton();
        rbPessoaFisica = new javax.swing.JRadioButton();
        rbPessoaJuridica = new javax.swing.JRadioButton();
        ftCnpj = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        ftRg = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        ftCep = new javax.swing.JFormattedTextField();
        btNovo = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCliente = new javax.swing.JTable();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 20)); // NOI18N
        jLabel1.setText("Cadastro de Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nome/Razão Social:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Sexo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("RG:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Telefone:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Celular:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Email:");

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        try {
            ftCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftCpfFocusLost(evt);
            }
        });
        ftCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftCpfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftCpfKeyTyped(evt);
            }
        });

        try {
            ftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Pesquisar.jpg"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        bgSexo.add(rbMasc);
        rbMasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbMasc.setSelected(true);
        rbMasc.setText("Masculino");

        bgSexo.add(rbFem);
        rbFem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbFem.setText("Feminino");

        buttonGroup2.add(rbPessoaFisica);
        rbPessoaFisica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbPessoaFisica.setText("Fisíca");
        rbPessoaFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaFisicaActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbPessoaJuridica);
        rbPessoaJuridica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbPessoaJuridica.setText("Jurídica");
        rbPessoaJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPessoaJuridicaActionPerformed(evt);
            }
        });

        try {
            ftCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("CNPJ:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Pessoa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ftRg, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(rbMasc)
                                .addGap(34, 34, 34)
                                .addComponent(rbFem))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(btBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPessoaFisica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbPessoaJuridica))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(ftCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbMasc)
                    .addComponent(rbFem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rbPessoaFisica)
                    .addComponent(rbPessoaJuridica))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(ftRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Endereço:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Cidade:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("CEP:");

        try {
            ftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEndereco))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftCep, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Novo.jpg"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Gravar.jpg"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Atualizar.jpg"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Excluir.jpg"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Limpar.jpg"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/voltar.jpg"))); // NOI18N
        btSair.setText("Voltar");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/carro.jpeg"))); // NOI18N
        jButton1.setText("Cadastrar Informações do Carro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jtCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCliente);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btSair))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        FormPrincipal.abrir();
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:
        if (tfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código.");
            tfCodigo.requestFocus();
            return;
        }
        if (tfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome.");
            tfNome.requestFocus();
            return;
        }
        if (ftRg.getText().equals("         ")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo RG.");
            ftRg.requestFocus();
            return;
        }
        if (ftCelular.getText().equals("(  )      -    ")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Celular.");
            ftCelular.requestFocus();
            return;
        }
        if (tfEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Endereco.");
            tfEndereco.requestFocus();
            return;
        }
        if (tfCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Cidade.");
            tfCidade.requestFocus();
            return;
        }
        if (ftCep.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CEP.");
            ftCep.requestFocus();
            return;
        }
        clienteDAO.cliente.setCodigo(tfCodigo.getText());
        clienteDAO.cliente.setNome(tfNome.getText());
        clienteDAO.cliente.setEmail(tfEmail.getText());
        if (rbMasc.isSelected()) {
            clienteDAO.cliente.setSexo("M");
        } else if (rbFem.isSelected()) {
            clienteDAO.cliente.setSexo("F");
        }
        if (rbPessoaFisica.isSelected()) {
            clienteDAO.cliente.setPessoa("Física");
        } else if (rbPessoaJuridica.isSelected()) {
            clienteDAO.cliente.setPessoa("Jurídica");
        }
        clienteDAO.cliente.setCpf(ftCpf.getText());
        clienteDAO.cliente.setRg(ftRg.getText());
        clienteDAO.cliente.setCnpj(ftCnpj.getText());
        clienteDAO.cliente.setTelefone(ftTelefone.getText());
        clienteDAO.cliente.setCelular(ftCelular.getText());
        clienteDAO.cliente.setEndereco(tfEndereco.getText());
        clienteDAO.cliente.setCidade(tfCidade.getText());
        clienteDAO.cliente.setCep(ftCep.getText());
        JOptionPane.showMessageDialog(null, clienteDAO.inserirCliente());
        limpaCampos();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        if (tfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código.");
            tfCodigo.requestFocus();
            return;
        }
        if (tfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome.");
            tfNome.requestFocus();
            return;
        }
        if (rbMasc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Sexo.");
            tfCodigo.requestFocus();
            return;
        }
        if (rbFem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Sexo.");
            tfCodigo.requestFocus();
            return;
        }
        if (ftCelular.getText().equals("(  )      -    ")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Celular.");
            ftCelular.requestFocus();
            return;
        }
        if (tfEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Endereco.");
            tfEndereco.requestFocus();
            return;
        }
        if (tfCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Cidade.");
            tfCidade.requestFocus();
            return;
        }
        if (ftCep.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CEP.");
            ftCep.requestFocus();
            return;
        }
        clienteDAO.cliente.setCodigo(tfCodigo.getText());
        clienteDAO.cliente.setNome(tfNome.getText());
        clienteDAO.cliente.setEmail(tfEmail.getText());
        if (rbMasc.isSelected()) {
            clienteDAO.cliente.setSexo("M");
        } else if (rbFem.isSelected()) {
            clienteDAO.cliente.setSexo("F");
        }
        if (rbPessoaFisica.isSelected()) {
            clienteDAO.cliente.setPessoa("Física");
        } else if (rbPessoaJuridica.isSelected()) {
            clienteDAO.cliente.setPessoa("Jurídica");
        }
        clienteDAO.cliente.setCpf(ftCpf.getText());
        clienteDAO.cliente.setRg(ftRg.getText());
        clienteDAO.cliente.setCnpj(ftCnpj.getText());
        clienteDAO.cliente.setTelefone(ftTelefone.getText());
        clienteDAO.cliente.setCelular(ftCelular.getText());
        clienteDAO.cliente.setEndereco(tfEndereco.getText());
        clienteDAO.cliente.setCidade(tfCidade.getText());
        clienteDAO.cliente.setCep(ftCep.getText());
        JOptionPane.showMessageDialog(null, clienteDAO.atualizarCliente());
        limpaCampos();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (tfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite o código do cliente a ser excluido.");
            tfCodigo.requestFocus();
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja Excluir?", "ALERTA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == 0) {
            clienteDAO.cliente.setCodigo("" + tfCodigo.getText());
            clienteDAO.excluirAgendamento();
            clienteDAO.excluirCarro();
            JOptionPane.showMessageDialog(null, clienteDAO.excluirCliente());
            limpaCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não excluido.");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        tfCodigo.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        String codigoNovo;
        codigoNovo = "" + clienteDAO.proximoCliente();
        if (!codigoNovo.equals("0")) {
            tfCodigo.setText(codigoNovo);
            tfNome.requestFocus();
            campoDesa(false);
        }
    }//GEN-LAST:event_btNovoActionPerformed

    private void jtClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClienteMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jtCliente.getSelectedRow();
        if (linhaSelecionada >= 0) {
            tfCodigo.setText(jtCliente.getValueAt(linhaSelecionada, 0).toString());
            tfNome.setText(jtCliente.getValueAt(linhaSelecionada, 1).toString());
            tfEmail.setText(jtCliente.getValueAt(linhaSelecionada, 2).toString());
            String sexoSelecionado = (jtCliente.getValueAt(linhaSelecionada, 3).toString());
            if ("M".equals(sexoSelecionado)) {
                rbMasc.setSelected(true);
            } else {
                rbFem.setSelected(true);
            }
            String fjSelecionado = (jtCliente.getValueAt(linhaSelecionada, 4).toString());
            if ("Física".equals(fjSelecionado)) {
                rbPessoaFisica.setSelected(true);
                ftCpf.setText(jtCliente.getValueAt(linhaSelecionada, 5).toString());
                ftRg.setText(jtCliente.getValueAt(linhaSelecionada, 6).toString());
                limpacamposFisico();
                camposPessoa(true, false, true);
            } else {
                rbPessoaJuridica.setSelected(true);
                ftCnpj.setText(jtCliente.getValueAt(linhaSelecionada, 7).toString());
                limpacamposJuridico();
                camposPessoa(false, true, false);
            }
            ftTelefone.setText(jtCliente.getValueAt(linhaSelecionada, 8).toString());
            ftCelular.setText(jtCliente.getValueAt(linhaSelecionada, 9).toString());
            tfEndereco.setText(jtCliente.getValueAt(linhaSelecionada, 10).toString());
            tfCidade.setText(jtCliente.getValueAt(linhaSelecionada, 11).toString());
            ftCep.setText(jtCliente.getValueAt(linhaSelecionada, 12).toString());
        }
    }//GEN-LAST:event_jtClienteMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String sql = "select * from cliente";
        preencherTabela(sql);
//        camposPessoa(false, false, false);
    }//GEN-LAST:event_formWindowActivated

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        if (tfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira o Código do Cliente");
            tfCodigo.requestFocus();
            if (!tfCodigo.getText().equals("")) {
                clienteDAO.cliente.setCodigo(tfCodigo.getText());
                if (clienteDAO.localizarCliente()) {
                    tfCodigo.setText(clienteDAO.cliente.getCodigo());
                    tfNome.setText(clienteDAO.cliente.getNome());
                    tfEmail.setText(clienteDAO.cliente.getEmail());
                    if (clienteDAO.cliente.getSexo().equals("M")) {
                        rbMasc.setSelected(true);
                    } else {
                        rbFem.setSelected(true);
                    }
                    if (clienteDAO.cliente.getPessoa().equals("Física")) {
                        rbPessoaFisica.setSelected(true);
                        ftCpf.setText(clienteDAO.cliente.getCpf());
                        ftRg.setText(clienteDAO.cliente.getRg());
                        limpacamposFisico();
                        camposSexo(true, true);
                        camposPessoa(true, false, true);
                    } else {
                        rbPessoaJuridica.setSelected(true);
                        ftCnpj.setText(clienteDAO.cliente.getCnpj());
                        limpacamposJuridico();
                        camposSexo(false, false);
                        camposPessoa(false, true, false);
                    }
                    ftTelefone.setText(clienteDAO.cliente.getTelefone());
                    ftCelular.setText(clienteDAO.cliente.getCelular());
                    tfEndereco.setText(clienteDAO.cliente.getEndereco());
                    tfCidade.setText(clienteDAO.cliente.getCidade());
                    ftCep.setText(clienteDAO.cliente.getCep());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");
            atualizaCampos();
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CadastroCarro.abrir();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbPessoaFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaFisicaActionPerformed
        // TODO add your handling code here:
        if (rbPessoaFisica.isSelected()) {
            camposPessoa(true, false, true);
            camposSexo(true, true);
        }
    }//GEN-LAST:event_rbPessoaFisicaActionPerformed

    private void rbPessoaJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPessoaJuridicaActionPerformed
        // TODO add your handling code here:
        if (rbPessoaJuridica.isSelected()) {
            camposPessoa(false, true, false);
            camposSexo(false, false);
        }
    }//GEN-LAST:event_rbPessoaJuridicaActionPerformed

    private void ftCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftCpfKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ftCpfKeyTyped

    private void ftCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftCpfKeyReleased
        // TODO add your handling code here:
        if (a != 1) {
            if (!ftCpf.getText().equals("   .   .   -  ")) {
                String cpf = ftCpf.getText();
                cpf = cpf.replace(".", "");
                cpf = cpf.replace("-", "");
                ValidarCPF valCpf = new ValidarCPF() {
                };
                if (valCpf.validaCPF(cpf) == true) {

                    conecta.conectarBD();
                    String buscaCpf = ftCpf.getText();
                    PreparedStatement sta;
                    try {
                        sta = conecta.connection.prepareStatement("select * from cliente where cpf = ? ");
                        sta.setString(1, buscaCpf);
                        ResultSet rs = sta.executeQuery();
                        while (rs.next()) {
                            JOptionPane.showMessageDialog(null, "CPF já cadastrado anteriormente!");
                            ftCpf.setValue("");
                            ftCpf.grabFocus();
                        }
                    } catch (SQLException ex) {
                    }
                } else {

                }
            }
        } else if (!ftCpf.getText().equals("   .   .   -  ")) {
            String cpf = ftCpf.getText();
            cpf = cpf.replace(".", "");
            cpf = cpf.replace("-", "");
            ValidarCPF valCpf = new ValidarCPF() {
            };
            if (valCpf.validaCPF(cpf) == true) // jLabelValCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/102.png")));
            {
                // jLabelValCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/101.png")));

            }
        }
    }//GEN-LAST:event_ftCpfKeyReleased

    private void ftCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftCpfFocusLost
        // TODO add your handling code here:      
        if (a != 1) {
            if (!ftCpf.getText().equals("   .   .   -  ")) {
                String cpf = ftCpf.getText();
                cpf = cpf.replace(".", "");
                cpf = cpf.replace("-", "");
                ValidarCPF valCpf = new ValidarCPF() {
                };
                if (valCpf.validaCPF(cpf) == false) {
                    JOptionPane.showMessageDialog(null, "Entre com o CPF válido!");
                    ftCpf.grabFocus();
                }
            }
        } else if (!ftCpf.getText().equals("   .   .   -  ")) {
            String cpf = ftCpf.getText();
            cpf = cpf.replace(".", "");
            cpf = cpf.replace("-", "");
            ValidarCPF valCpf = new ValidarCPF() {
            };
            if (valCpf.validaCPF(cpf) == false) {
                JOptionPane.showMessageDialog(null, "Entre com o CPF válido!");
                ftCpf.grabFocus();
            } else {
                // pesquisaCpf();
            }
        } else {
            // jTextFieldNome.grabFocus();
        }
    }//GEN-LAST:event_ftCpfFocusLost
    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"CÓDIGO", "NOME", "EMAIL", "SEXO", "PESSOA", "CPF", "RG", "CNPJ", "TELEFONE", "CELULAR", "ENDERECO", "CIDADE", "CEP"};
        clienteDAO.pesquisarCliente(sql);
        try {
            clienteDAO.resultSet.first();
            do {
                dados.add(new Object[]{
                    clienteDAO.resultSet.getInt("codigo"),
                    clienteDAO.resultSet.getString("nome"),
                    clienteDAO.resultSet.getString("email"),
                    clienteDAO.resultSet.getString("sexo"),
                    clienteDAO.resultSet.getString("pessoa"),
                    clienteDAO.resultSet.getString("cpf"),
                    clienteDAO.resultSet.getString("rg"),
                    clienteDAO.resultSet.getString("cnpj"),
                    clienteDAO.resultSet.getString("telefone"),
                    clienteDAO.resultSet.getString("celular"),
                    clienteDAO.resultSet.getString("endereco"),
                    clienteDAO.resultSet.getString("cidade"),
                    clienteDAO.resultSet.getString("cep"),});
            } while (clienteDAO.resultSet.next());
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro: \n" + erro);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jtCliente.setModel(modelo);
        jtCliente.getColumnModel().getColumn(0).setPreferredWidth(60);
        jtCliente.getColumnModel().getColumn(0).setResizable(false);
        jtCliente.getColumnModel().getColumn(1).setPreferredWidth(200);
        jtCliente.getColumnModel().getColumn(1).setResizable(true);
        jtCliente.getColumnModel().getColumn(2).setPreferredWidth(120);
        jtCliente.getColumnModel().getColumn(2).setResizable(false);
        jtCliente.getColumnModel().getColumn(3).setPreferredWidth(50);
        jtCliente.getColumnModel().getColumn(3).setResizable(false);
        jtCliente.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtCliente.getColumnModel().getColumn(4).setResizable(false);
        jtCliente.getColumnModel().getColumn(5).setPreferredWidth(130);
        jtCliente.getColumnModel().getColumn(5).setResizable(false);
        jtCliente.getColumnModel().getColumn(6).setPreferredWidth(130);
        jtCliente.getColumnModel().getColumn(6).setResizable(false);
        jtCliente.getColumnModel().getColumn(7).setPreferredWidth(130);
        jtCliente.getColumnModel().getColumn(7).setResizable(false);
        jtCliente.getColumnModel().getColumn(8).setPreferredWidth(180);
        jtCliente.getColumnModel().getColumn(8).setResizable(false);
        jtCliente.getColumnModel().getColumn(9).setPreferredWidth(130);
        jtCliente.getColumnModel().getColumn(9).setResizable(false);
        jtCliente.getColumnModel().getColumn(10).setPreferredWidth(130);
        jtCliente.getColumnModel().getColumn(10).setResizable(false);
        jtCliente.getColumnModel().getColumn(11).setPreferredWidth(130);
        jtCliente.getColumnModel().getColumn(11).setResizable(false);
        jtCliente.getColumnModel().getColumn(12).setPreferredWidth(130);
        jtCliente.getColumnModel().getColumn(12).setResizable(false);
        jtCliente.getTableHeader().setReorderingAllowed(false);
        jtCliente.setAutoResizeMode(jtCliente.AUTO_RESIZE_OFF);
        jtCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        clienteDAO.conecta.fecharBD();
    }

    public void campoDesa(boolean cCgodio) {
        tfCodigo.setEnabled(cCgodio);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    public void limpaCampos() {
        tfCodigo.setText("");
        tfNome.setText("");
        tfEmail.setText("");
        rbMasc.setSelected(true);
        rbFem.setSelected(false);
        rbPessoaFisica.setSelected(false);
        rbPessoaJuridica.setSelected(false);
        ftCnpj.setText("");
        ftCpf.setText("");
        ftRg.setText("");
        ftTelefone.setText("");
        ftCelular.setText("");
        tfEndereco.setText("");
        tfCidade.setText("");
        ftCep.setText("");
    }

    public void atualizaCampos() {
        clienteDAO.cliente.setCodigo(tfCodigo.getText());
        if (clienteDAO.localizarCliente()) {
            clienteDAO.cliente.setCodigo(tfCodigo.getText());
            clienteDAO.cliente.setNome(tfNome.getText());
            clienteDAO.cliente.setEmail(tfEmail.getText());
            if (rbMasc.isSelected()) {
                clienteDAO.cliente.setSexo("M");
            } else if (rbFem.isSelected()) {
                clienteDAO.cliente.setSexo("F");
            }
            if (rbPessoaFisica.isSelected()) {
                clienteDAO.cliente.setPessoa("Física");
            } else if (rbPessoaJuridica.isSelected()) {
                clienteDAO.cliente.setPessoa("Jurídica");
            }
            clienteDAO.cliente.setCpf(ftCpf.getText());
            clienteDAO.cliente.setRg(ftRg.getText());
            clienteDAO.cliente.setCnpj(ftCnpj.getText());
            clienteDAO.cliente.setTelefone(ftTelefone.getText());
            clienteDAO.cliente.setCelular(ftCelular.getText());
            clienteDAO.cliente.setEndereco(tfEndereco.getText());
            clienteDAO.cliente.setCidade(tfCidade.getText());
            clienteDAO.cliente.setCep(ftCep.getText());
        } else {
            limpaCampos();
        }
    }

    public void camposPessoa(boolean bCpf, boolean bCnpj, boolean bRg) {
        ftCnpj.setEnabled(bCnpj);
        ftCpf.setEnabled(bCpf);
        ftRg.setEnabled(bRg);
    }

    public void limpacamposFisico() {
        ftCnpj.setText("");
    }

    public void limpacamposJuridico() {
        ftCpf.setText("");
        ftRg.setText("");
    }

    public void camposSexo(boolean tMasc, boolean tFem) {
        rbMasc.setEnabled(tMasc);
        rbFem.setEnabled(tFem);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField ftCelular;
    private javax.swing.JFormattedTextField ftCep;
    private javax.swing.JFormattedTextField ftCnpj;
    private javax.swing.JFormattedTextField ftCpf;
    private javax.swing.JTextField ftRg;
    private javax.swing.JFormattedTextField ftTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCliente;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JRadioButton rbPessoaFisica;
    private javax.swing.JRadioButton rbPessoaJuridica;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
