/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopecas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.Timer;

/**
 *
 * @author LG
 */
public class CadastroOS extends javax.swing.JFrame {

    static void abrir() {
        CadastroOS frame = new CadastroOS();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* capturando o tamanho da tela onde está rodando este programa */
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((tela.width - frame.getSize().width) / 2,
                (tela.height - frame.getSize().height) / 2);
        frame.setVisible(true);
    }

    /**
     * Creates new form CadastroOS
     */
    private osDAO OsDAO;

    public CadastroOS() {
        initComponents();
        OsDAO = new osDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNovo = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ftHoraEntrega = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        tfCodigo = new javax.swing.JTextField();
        tfMatriculaFuncionario = new javax.swing.JTextField();
        tfCodigoAgenda = new javax.swing.JTextField();
        ftDataEntrega = new javax.swing.JFormattedTextField();
        tfValorTotal = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTOS = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Novo.jpg"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Atualizar.jpg"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Gravar.jpg"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Excluir.jpg"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Limpar.jpg"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/voltar.jpg"))); // NOI18N
        jButton6.setText("Voltar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 20)); // NOI18N
        jLabel7.setText("Ordem de Serviços");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        try {
            ftHoraEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Data Entrega:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Valor Total:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Hora Entrega:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Código Agenda:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Matrícula Funcionário:");

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Pesquisar.jpg"))); // NOI18N
        btPesquisar.setText("Buscar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        try {
            ftDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Código:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar)
                    .addComponent(jLabel2)
                    .addComponent(ftDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(ftHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCodigoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTOS.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTOSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTOS);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
                            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String sql = "select * from os";
        preencherTabela(sql);
    }//GEN-LAST:event_formWindowActivated

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        String codigoNovo;
        codigoNovo = "" + OsDAO.proximoOS();
//        limpaCampos();
        if (!codigoNovo.equals("0")) {
            tfCodigo.setText(codigoNovo);
        }
        Timer timer = new Timer(1000, new CadastroOS.hora());
        timer.start();
//        HabilitaCampos(false);
        limpaCampos();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        if (!tfCodigo.getText().equals("")) {
            OsDAO.os.setCodigo(tfCodigo.getText());
            if (OsDAO.localizarOS()) {
                tfCodigo.setText(OsDAO.os.getCodigo());
                ftDataEntrega.setText(OsDAO.os.getDataEntrega());
                tfValorTotal.setText(OsDAO.os.getValorTotal());
                ftHoraEntrega.setText(OsDAO.os.getHoraEntrega());
                tfCodigoAgenda.setText(OsDAO.os.getCodigoAgenda());
                tfMatriculaFuncionario.setText(OsDAO.os.getMatriculaFuncionario());
            }
        }
        atualizaCampos();

    }//GEN-LAST:event_btPesquisarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        FormPrincipal.abrir();
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (ftDataEntrega.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Preencha com a Data da entrega.");
            ftDataEntrega.requestFocus();
            return;
        }
        if (tfValorTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Valor Total.");
            tfValorTotal.requestFocus();
            return;
        }
        if (ftHoraEntrega.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preecha com a hora da entrga.");
            ftHoraEntrega.requestFocus();
            return;
        }
        /* if (tfCodigoAgenda.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Codigo Agenda.");
            tfCodigoAgenda.requestFocus();
            return;
        }
        if (tfMatriculaFuncionario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Matricula Funcioanario.");
            tfMatriculaFuncionario.requestFocus();
            return;
        }*/
        //Preenchendo os atributos do obejto filme (instanciando da Classe Funcionario)

        OsDAO.os.setCodigo(tfCodigo.getText());
        String dataEN = FormatDateEN(ftDataEntrega.getText());
        OsDAO.os.setDataEntrega(dataEN);
        OsDAO.os.setHoraEntrega(ftHoraEntrega.getText());
        OsDAO.os.setCodigoAgenda(tfCodigoAgenda.getText());
        OsDAO.os.setMatriculaFuncionario(tfMatriculaFuncionario.getText());
        String valorV = FormataV(tfValorTotal.getText());
        OsDAO.os.setValorTotal(valorV);
        JOptionPane.showMessageDialog(null, OsDAO.incluirOS());
//        limpaCampos();
        String sql = "select * from os";

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        if (ftDataEntrega.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Preencha com a Data da entrega.");
            ftDataEntrega.requestFocus();
            return;
        }
        if (tfValorTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Valor Total.");
            tfValorTotal.requestFocus();
            return;
        }
        if (ftHoraEntrega.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preecha com a hora da entrga.");
            ftHoraEntrega.requestFocus();
            return;
        }
        /* if (tfCodigoAgenda.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Codigo Agenda.");
            tfCodigoAgenda.requestFocus();
            return;
        }
        if (tfMatriculaFuncionario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Matricula Funcioanario.");
            tfMatriculaFuncionario.requestFocus();
            return;
        }*/
        //Preenchendo os atributos do obejto filme (instanciando da Classe Funcionario)

        OsDAO.os.setCodigo(tfCodigo.getText());
        String dataEN = FormatDateEN(ftDataEntrega.getText());
        OsDAO.os.setDataEntrega(dataEN);
        OsDAO.os.setHoraEntrega(ftHoraEntrega.getText());
        OsDAO.os.setCodigoAgenda(tfCodigoAgenda.getText());
        OsDAO.os.setMatriculaFuncionario(tfMatriculaFuncionario.getText());
        String valorV = FormataV(tfValorTotal.getText());
        OsDAO.os.setValorTotal(valorV);
        JOptionPane.showMessageDialog(null, OsDAO.atualizaOS());
//        limpaCampos();
        String sql = "select * from os";
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (tfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código.");
            tfCodigo.requestFocus();
            return;
        }
        // Função OK_CANCEL_OPTION  para colocar um janela com opções "SIM" para excuir e "NÂO" para não exlcuir
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir esta Ordem de Serviço  ?", "", JOptionPane.OK_CANCEL_OPTION);
        if (resposta == 0) {
            OsDAO.os.setCodigo(tfCodigo.getText());
            JOptionPane.showMessageDialog(null, OsDAO.excluiOS());
//            limpaCampos();
            String sql = "select * from os";
            //preecherTabela(sql);

        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void jTOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTOSMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jTOS.getSelectedRow();
        if (linhaSelecionada >= 0) {
            tfCodigo.setText(jTOS.getValueAt(linhaSelecionada, 0).toString());
            ftDataEntrega.setText(jTOS.getValueAt(linhaSelecionada, 1).toString());
            tfValorTotal.setText(jTOS.getValueAt(linhaSelecionada, 2).toString());
            ftHoraEntrega.setText(jTOS.getValueAt(linhaSelecionada, 3).toString());
            tfCodigoAgenda.setText(jTOS.getValueAt(linhaSelecionada, 4).toString());
            tfMatriculaFuncionario.setText(jTOS.getValueAt(linhaSelecionada, 5).toString());
        }
    }//GEN-LAST:event_jTOSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroOS().setVisible(true);
            }
        });
    }

    class hora implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            ftHoraEntrega.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

    public void limpaCamposNovo(boolean data, boolean hora) {
        ftDataEntrega.setText("");
        ftHoraEntrega.setText("");
    }

    public void limpaCampos() {
        tfCodigo.setText("");
        ftDataEntrega.setText("");
        tfValorTotal.setText("");
        ftHoraEntrega.setText("");
        tfCodigoAgenda.setText("");
        tfMatriculaFuncionario.setText("");
        tfCodigo.requestFocus();
    }

    public void atualizaCampos() {
        OsDAO.os.setCodigo(tfCodigo.getText());
        if (OsDAO.localizarOS()) {
            OsDAO.os.setCodigo(tfCodigo.getText());
            String dataEN = FormatDateEN(ftDataEntrega.getText());
            OsDAO.os.setDataEntrega(dataEN);
            OsDAO.os.setValorTotal(tfValorTotal.getText());
            OsDAO.os.setHoraEntrega(ftHoraEntrega.getText());
            OsDAO.os.setCodigoAgenda(tfCodigoAgenda.getText());
            OsDAO.os.setMatriculaFuncionario(tfMatriculaFuncionario.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Ordem de Serviço não encontrada.");
            limpaCampos();
        }
    }

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"CÓDIGO", "DATA ENTREGA", "VALOR TOTAL", "HORA ENTREGA", "CÓDIGO AGENDA", "MATRÍCULA FUNCIONÁRIO"};
        OsDAO.pesquisarOS(sql);
        try {
            OsDAO.resultSet.first();
            do {
                String dataBR = FormatDateBR(OsDAO.resultSet.getString("dataEntrega"));
                String valorP = FormataTabela(OsDAO.resultSet.getString("valorTotal"));
                dados.add(new Object[]{
                    OsDAO.resultSet.getInt("codigo"),
                    dataBR,
                    valorP,
                    OsDAO.resultSet.getString("horaEntrega"),
                    OsDAO.resultSet.getString("fkAgenda"),
                    OsDAO.resultSet.getString("funcionario_matricula"),});
            } while (OsDAO.resultSet.next());
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro: \n" + erro);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTOS.setModel(modelo);
        jTOS.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTOS.getColumnModel().getColumn(0).setResizable(false);
        jTOS.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTOS.getColumnModel().getColumn(1).setResizable(true);
        jTOS.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTOS.getColumnModel().getColumn(2).setResizable(false);
        jTOS.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTOS.getColumnModel().getColumn(3).setResizable(false);
        jTOS.getColumnModel().getColumn(4).setPreferredWidth(120);
        jTOS.getColumnModel().getColumn(4).setResizable(false);
        jTOS.getColumnModel().getColumn(5).setPreferredWidth(165);
        jTOS.getColumnModel().getColumn(5).setResizable(false);
        jTOS.setAutoResizeMode(jTOS.AUTO_RESIZE_OFF);
        jTOS.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        OsDAO.conecta.fecharBD();
    }

    public String FormatDateBR(String dataEN) {
        String dataBR = dataEN;
        dataBR = dataBR.substring(8, 10) + "/"
                + dataBR.substring(5, 7) + "/"
                + dataBR.substring(0, 4);
        return dataBR;
    }

    //Formantando do padrão 'BRASILEIRO' para o padrão 'AMERICANO'
    public String FormatDateEN(String dataBR) {
        String dataEN = dataBR;
        dataEN = dataEN.substring(6, 10) + "/"
                + dataEN.substring(3, 5) + "/"
                + dataEN.substring(0, 2);
        return dataEN;
    }

    public void HabilitaCampos(boolean cCodigo, boolean cHora) {
        tfCodigo.setEnabled(cCodigo);
        ftHoraEntrega.setEnabled(cHora);
    }

    public String FormataV(String valorP) {
        String valorV = (tfValorTotal.getText().replace(",", ".").toString());
        return valorV;
    }

    public String FormataTabela(String valorP) {
        String valorV = valorP.replace(".", ",");
        return valorV;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JFormattedTextField ftDataEntrega;
    private javax.swing.JFormattedTextField ftHoraEntrega;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTOS;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCodigoAgenda;
    private javax.swing.JTextField tfMatriculaFuncionario;
    private javax.swing.JFormattedTextField tfValorTotal;
    // End of variables declaration//GEN-END:variables
}
