/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopecas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author nicol
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    int a;
    int b;
    ConectaBD conecta = new ConectaBD();

    static void abrir() {

        CadastroFuncionario frame = new CadastroFuncionario();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* capturando o tamanho da tela onde está rodando este programa */
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((tela.width - frame.getSize().width) / 2,
                (tela.height - frame.getSize().height) / 2);
        frame.setVisible(true);

    }
    private FuncionarioDAO funcionarioDAO;

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
        funcionarioDAO = new FuncionarioDAO();
        HabilitaCampos(true, true, true, true);
        setTitle("Sistema de Cadastro de Funcionários- Elite Auto-Car");
        conecta.conectarBD();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        bgSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ftCpf = new javax.swing.JFormattedTextField();
        tfMatricula = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        tfCelular = new javax.swing.JFormattedTextField();
        ftCep = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        rbMasc = new javax.swing.JRadioButton();
        rbFem = new javax.swing.JRadioButton();
        ftDataNascimento = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        tfUsuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ftRg = new javax.swing.JTextField();
        cbPerfil = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ftDataAdmissao = new javax.swing.JFormattedTextField();
        cbCargo = new javax.swing.JComboBox<>();
        tfCarteiraTrabalho = new javax.swing.JTextField();
        tfSalario = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        btContratar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btDemitir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btListFunc = new javax.swing.JButton();

        jFormattedTextField4.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 20)); // NOI18N
        jLabel1.setText("Cadastro de Funcionários");
        jLabel1.setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Matricula:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Endereço:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Bairro:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("RG:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("CPF:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("CEP:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Celular:");

        try {
            ftCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCpf.setPreferredSize(new java.awt.Dimension(110, 20));
        ftCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftCpfFocusLost(evt);
            }
        });
        ftCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ftCpfKeyReleased(evt);
            }
        });

        tfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEnderecoActionPerformed(evt);
            }
        });

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCelular.setPreferredSize(new java.awt.Dimension(110, 20));

        try {
            ftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCep.setPreferredSize(new java.awt.Dimension(110, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Sexo:");

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Pesquisar.jpg"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        bgSexo.add(rbMasc);
        rbMasc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbMasc.setSelected(true);
        rbMasc.setText("Masculino");

        bgSexo.add(rbFem);
        rbFem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbFem.setText("Feminino");

        try {
            ftDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDataNascimento.setMinimumSize(new java.awt.Dimension(6, 25));
        ftDataNascimento.setPreferredSize(new java.awt.Dimension(110, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Data de Nascimento:");

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfTelefone.setPreferredSize(new java.awt.Dimension(110, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Telefone:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cidade:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Usuário:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Perfil:");

        cbPerfil.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Comum" }));
        cbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBairro)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfEndereco)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ftRg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbMasc)
                        .addGap(18, 18, 18)
                        .addComponent(rbFem, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(cbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBuscar)
                        .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(rbMasc)
                    .addComponent(rbFem)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(ftDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ftRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Data de Admissão:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Cargo:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Carteira de Trabalho:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Salario:");

        try {
            ftDataAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbCargo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Mecânico", "Pintor", "Gerente", "Tesoureiro" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCarteiraTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(ftDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(tfCarteiraTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Novo.jpg"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btContratar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btContratar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Contratar.jpg"))); // NOI18N
        btContratar.setText("Contratar");
        btContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContratarActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Atualizar.jpg"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btDemitir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btDemitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Demitir.jpg"))); // NOI18N
        btDemitir.setText("Demitir");
        btDemitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDemitirActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Limpar.jpg"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/voltar.jpg"))); // NOI18N
        btSair.setText("Voltar");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btListFunc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btListFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/listFunc.jpeg"))); // NOI18N
        btListFunc.setText("Ver Lista de Funcionários");
        btListFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(266, 266, 266))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btContratar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDemitir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btListFunc))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btContratar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDemitir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btListFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        FormPrincipal.abrir();
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed

        // TODO add your handling code here:
        //String sql = "select * from funcionario where matricula = " + tfMatricula.getText();
        //preecherTabela(sql);
        if (tfMatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira a Matrícula do Funcionário");
            requestFocus();
            if (!tfMatricula.getText().equals("")) {
                funcionarioDAO.funcionario.setMatricula(tfMatricula.getText());
                if (funcionarioDAO.localizarFuncionario()) {
                    tfMatricula.setText(funcionarioDAO.funcionario.getMatricula());
                    tfNome.setText(funcionarioDAO.funcionario.getNome());
                    ftDataNascimento.setText(funcionarioDAO.funcionario.getDataNascimento());
                    if (funcionarioDAO.funcionario.getSexo().equals("M")) {
                        rbMasc.setSelected(true);
                    } else {
                        rbFem.setSelected(true);
                    }
                    tfTelefone.setText(funcionarioDAO.funcionario.getTelefone());
                    tfCelular.setText(funcionarioDAO.funcionario.getCelular());
                    ftCpf.setText(funcionarioDAO.funcionario.getCpf());
                    ftRg.setText(funcionarioDAO.funcionario.getRg());
                    ftCep.setText(funcionarioDAO.funcionario.getCep());
                    tfEndereco.setText(funcionarioDAO.funcionario.getEndereco());
                    tfBairro.setText(funcionarioDAO.funcionario.getBairro());
                    tfCidade.setText(funcionarioDAO.funcionario.getCidade());
                    ftDataAdmissao.setText(funcionarioDAO.funcionario.getDataAdmissao());
                    tfCarteiraTrabalho.setText(funcionarioDAO.funcionario.getCarteiraTrabalho());
                    cbCargo.setSelectedItem(funcionarioDAO.funcionario.getCargo());
                    tfSalario.setText(funcionarioDAO.funcionario.getSalario());
                    tfUsuario.setText(funcionarioDAO.funcionario.getUsuario());
                    if (funcionarioDAO.funcionario.getPerfil().equals("1")) {
                        cbPerfil.setSelectedItem("Administrador");
                    } else if (funcionarioDAO.funcionario.getPerfil().equals("2")) {
                        cbPerfil.setSelectedItem("Comum");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Funcionário não encontrado");
            atualizaCampos();
        }

    }//GEN-LAST:event_btBuscarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        String codigoNovo;
        codigoNovo = "" + funcionarioDAO.proximoFuncionario();
        limpaCampos();
        if (!codigoNovo.equals("0")) {
            tfMatricula.setText(codigoNovo);
            tfNome.requestFocus();
        }
        HabilitaCampos(false, true, true, true);

    }//GEN-LAST:event_btNovoActionPerformed

    private void btContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContratarActionPerformed
        // TODO add your handling code here:
        if (tfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha com o nome do Funcionário.");
            tfNome.requestFocus();
            return;
        }
        if (ftDataNascimento.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Data nascimento.");
            ftDataNascimento.requestFocus();
            return;
        }
        if (tfCelular.getText().equals("(  )      -    ")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Celular.");
            tfCelular.requestFocus();
            return;
        }
        if (ftCpf.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(null, "Insira um CPF.");
            ftCpf.requestFocus();
            return;
        }
        if (ftRg.getText().equals(" .   .   ")) {
            JOptionPane.showMessageDialog(null, "Insira um RG.");
            ftRg.requestFocus();
            return;
        }
        if (ftCep.getText().equals("  .   -   ")) {
            JOptionPane.showMessageDialog(null, "Insira um Cep.");
            ftCep.requestFocus();
            return;
        }
        if (tfEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira um Endereço.");
            tfEndereco.requestFocus();
            return;
        }
        if (tfBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira um Bairro.");
            tfBairro.requestFocus();
            return;
        }
        if (tfCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira uma Cidade.");
            tfCidade.requestFocus();
            return;
        }
        if (ftDataAdmissao.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Insira uma Data de Admissão.");
            ftDataAdmissao.requestFocus();
            return;
        }
        if (tfCarteiraTrabalho.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo carteira de trabalho.");
            tfCarteiraTrabalho.requestFocus();
            return;
        }
        if (cbCargo.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um Cargo.");
            cbCargo.requestFocus();
            return;
        }
        if (tfSalario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo salário.");
            tfSalario.requestFocus();
            return;
        }
        if (cbPerfil.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um tipo de perfil");
            cbPerfil.requestFocus();
        }

        //Preenchendo os atributos do obejto filme (instanciando da Classe Funcionario)
        funcionarioDAO.funcionario.setMatricula(tfMatricula.getText());
        funcionarioDAO.funcionario.setNome(tfNome.getText());
        String dataEN = FormatDateEN(ftDataNascimento.getText());
        funcionarioDAO.funcionario.setDataNascimento(dataEN);
        if (rbMasc.isSelected()) {
            funcionarioDAO.funcionario.setSexo("M");
        } else if (rbFem.isSelected()) {
            funcionarioDAO.funcionario.setSexo("F");
        }
        funcionarioDAO.funcionario.setTelefone(tfTelefone.getText());
        funcionarioDAO.funcionario.setCelular(tfCelular.getText());
        funcionarioDAO.funcionario.setCpf(ftCpf.getText());
        funcionarioDAO.funcionario.setRg(ftRg.getText());
        funcionarioDAO.funcionario.setCep(ftCep.getText());
        funcionarioDAO.funcionario.setEndereco(tfEndereco.getText());
        funcionarioDAO.funcionario.setBairro(tfBairro.getText());
        funcionarioDAO.funcionario.setCidade(tfCidade.getText());
        String dataEN2 = FormatDateEN(ftDataAdmissao.getText());
        funcionarioDAO.funcionario.setDataAdmissao(dataEN2);
        funcionarioDAO.funcionario.setCarteiraTrabalho(tfCarteiraTrabalho.getText());
        funcionarioDAO.funcionario.setCargo(cbCargo.getSelectedItem().toString());
        String valorV = FormataV(tfSalario.getText());
        funcionarioDAO.funcionario.setSalario(valorV);
        funcionarioDAO.funcionario.setUsuario(tfUsuario.getText());
        funcionarioDAO.funcionario.setSenha("123456");
        if (cbPerfil.getSelectedItem().equals("Administrador")) {
            funcionarioDAO.funcionario.setPerfil("1");
        } else if (cbPerfil.getSelectedItem().equals("Comum")) {
            funcionarioDAO.funcionario.setPerfil("2");
        }
        JOptionPane.showMessageDialog(null, funcionarioDAO.incluirFuncionario());
        limpaCampos();
        String sql = "select * from funcionario";
        HabilitaCampos(true, true, true, true);
        //preecherTabela(sql);

    }//GEN-LAST:event_btContratarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        if (tfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha com o nome do Funcionário.");
            tfNome.requestFocus();;
            return;
        }
        if (ftDataNascimento.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Data nascimento.");
            ftDataNascimento.requestFocus();;
            return;
        }
        if (tfCelular.getText().equals("(  )     -    ")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Celular.");
            tfCelular.requestFocus();
            return;
        }
        if (ftCpf.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(null, "Insira um CPF.");
            ftCpf.requestFocus();
            return;
        }
        if (ftRg.getText().equals(" .   .   ")) {
            JOptionPane.showMessageDialog(null, "Insira um RG.");
            ftRg.requestFocus();
            return;
        }
        if (ftCep.getText().equals("  .   -   ")) {
            JOptionPane.showMessageDialog(null, "Insira um Cep.");
            ftCep.requestFocus();
            return;
        }
        if (tfEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira um Endereço.");
            tfEndereco.requestFocus();
            return;
        }
        if (tfBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira um Bairro.");
            tfBairro.requestFocus();
            return;
        }
        if (tfCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira uma Cidade.");
            tfCidade.requestFocus();
            return;
        }
        if (ftDataAdmissao.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Insira uma Data de Admissão.");
            ftDataAdmissao.requestFocus();
            return;
        }
        if (tfCarteiraTrabalho.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo carteira de trabalho.");
            tfCarteiraTrabalho.requestFocus();
            return;
        }
        if (cbCargo.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um cargo.");
            cbCargo.requestFocus();
            return;
        }
        if (tfSalario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo salário.");
            tfSalario.requestFocus();
            return;
        }
        //Preenchendo os atributos do obejto filme (instanciando da Classe Filme)
        funcionarioDAO.funcionario.setMatricula(tfMatricula.getText());
        funcionarioDAO.funcionario.setNome(tfNome.getText());
        String dataEN = FormatDateEN(ftDataNascimento.getText());
        funcionarioDAO.funcionario.setDataNascimento(dataEN);
        if (rbMasc.isSelected()) {
            funcionarioDAO.funcionario.setSexo("M");
        } else if (rbFem.isSelected()) {
            funcionarioDAO.funcionario.setSexo("F");
        }
        funcionarioDAO.funcionario.setTelefone(tfTelefone.getText());
        funcionarioDAO.funcionario.setCelular(tfCelular.getText());
        funcionarioDAO.funcionario.setCpf(ftCpf.getText());
        funcionarioDAO.funcionario.setRg(ftRg.getText());
        funcionarioDAO.funcionario.setCep(ftCep.getText());
        funcionarioDAO.funcionario.setEndereco(tfEndereco.getText());
        funcionarioDAO.funcionario.setBairro(tfBairro.getText());
        funcionarioDAO.funcionario.setCidade(tfCidade.getText());
        String dataEN2 = FormatDateEN(ftDataAdmissao.getText());
        funcionarioDAO.funcionario.setDataAdmissao(dataEN2);
        funcionarioDAO.funcionario.setCarteiraTrabalho(tfCarteiraTrabalho.getText());
        funcionarioDAO.funcionario.setCargo(cbCargo.getSelectedItem().toString());
        String valorV = FormataV(tfSalario.getText());
        funcionarioDAO.funcionario.setSalario(valorV);
        funcionarioDAO.funcionario.setUsuario(tfUsuario.getText());
        if (cbPerfil.getSelectedItem().equals("Administrador")) {
            funcionarioDAO.funcionario.setPerfil("1");
        }
        if (cbPerfil.getSelectedItem().equals("Comum")) {
            funcionarioDAO.funcionario.setPerfil("2");
        }
        JOptionPane.showMessageDialog(null, funcionarioDAO.atualizaFuncionario());
        limpaCampos();
        String sql = "select * from funcionario";
        //preecherTabela(sql);
        tfNome.requestFocus();
        HabilitaCampos(false, true, true, true);
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btDemitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDemitirActionPerformed
        // TODO add your handling code here:
        if (tfMatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Matrícula.");
            tfMatricula.requestFocus();
            return;
        }
        // Função OK_CANCEL_OPTION  para colocar um janela com opções "SIM" para excuir e "NÂO" para não exlcuir
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir este funcionário ?", "", JOptionPane.OK_CANCEL_OPTION);
        if (resposta == 0) {
            funcionarioDAO.funcionario.setMatricula(tfMatricula.getText());
            funcionarioDAO.excluiOS();
            JOptionPane.showMessageDialog(null, funcionarioDAO.excluiFuncionario());
            limpaCampos();
            String sql = "select * from funcionario";
            //preecherTabela(sql);

        }
    }//GEN-LAST:event_btDemitirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:[
        //String sql = "select * from funcionario";
//        preecherTabela(sql);


    }//GEN-LAST:event_formWindowActivated

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btListFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListFuncActionPerformed
        // TODO add your handling code here:
        TabelaListaFuncio.abrir();
        dispose();
    }//GEN-LAST:event_btListFuncActionPerformed

    private void tfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEnderecoActionPerformed

    private void cbPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPerfilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbPerfilActionPerformed

    private void ftCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftCpfFocusLost
        // TODO add your handling code here:
        if (a != 1) {
            if (!ftCpf.getText().equals("   .   .   -  ")) {
                String cpf = ftCpf.getText();
                cpf = cpf.replace(".", "");
                cpf = cpf.replace("-", "");
                ValidarCPF valCpf = new ValidarCPF() {
                };
                if (valCpf.validaCPF(cpf) == false) {
                    JOptionPane.showMessageDialog(null, "Entre com o CPF válido!");
                    ftCpf.grabFocus();
                }
            }
        } else if (!ftCpf.getText().equals("   .   .   -  ")) {
            String cpf = ftCpf.getText();
            cpf = cpf.replace(".", "");
            cpf = cpf.replace("-", "");
            ValidarCPF valCpf = new ValidarCPF() {
            };
            if (valCpf.validaCPF(cpf) == false) {
                JOptionPane.showMessageDialog(null, "Entre com o CPF válido!");
                ftCpf.grabFocus();
            } else {
                // pesquisaCpf();
            }
        } else {
            // jTextFieldNome.grabFocus();
        }
    }//GEN-LAST:event_ftCpfFocusLost

    private void ftCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftCpfKeyReleased
        // TODO add your handling code here:
        if (a != 1) {
            if (!ftCpf.getText().equals("   .   .   -  ")) {
                String cpf = ftCpf.getText();
                cpf = cpf.replace(".", "");
                cpf = cpf.replace("-", "");
                ValidarCPF valCpf = new ValidarCPF() {
                };
                if (valCpf.validaCPF(cpf) == true) {

                    conecta.conectarBD();
                    String buscaCpf = ftCpf.getText();
                    PreparedStatement sta;
                    try {
                        sta = conecta.connection.prepareStatement("select * from funcionario where cpf =?");
                        sta.setString(1, buscaCpf);
                        ResultSet rs = sta.executeQuery();
                        while (rs.next()) {
                            JOptionPane.showMessageDialog(null, "CPF já cadastrado anteriormente!");
                            ftCpf.setValue("");
                            ftCpf.grabFocus();
                        }
                    } catch (SQLException ex) {
                    }
                } else {

                }
            }
        } else if (!ftCpf.getText().equals("   .   .   -  ")) {
            String cpf = ftCpf.getText();
            cpf = cpf.replace(".", "");
            cpf = cpf.replace("-", "");
            ValidarCPF valCpf = new ValidarCPF() {
            };
            if (valCpf.validaCPF(cpf) == true) // jLabelValCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/102.png")));
            {
                // jLabelValCpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/101.png")));

            }
        }
    }//GEN-LAST:event_ftCpfKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    /*public void setCampos(boolean tMatricula) {
     tfMatricula.setEnabled(tMatricula);

     }*/
    public void limpaCampos() {
        tfMatricula.setText("");
        tfNome.setText("");
        ftDataNascimento.setText("");
        rbMasc.setSelected(false);
        rbFem.setSelected(false);
        tfTelefone.setText("");
        tfCelular.setValue("");
        ftCpf.setText("");
        ftRg.setText("");
        ftCep.setText("");
        tfEndereco.setText("");
        tfBairro.setText("");
        tfCidade.setText("");
        ftDataAdmissao.setText("");
        tfCarteiraTrabalho.setText("");
        cbCargo.setSelectedItem("Selecione");
        tfSalario.setText("");
        tfUsuario.setText("");
        cbPerfil.setSelectedItem("Selecione");
        tfMatricula.requestFocus();
    }

    public void atualizaCampos() {
        funcionarioDAO.funcionario.setMatricula(tfMatricula.getText());
        if (funcionarioDAO.localizarFuncionario()) {
            funcionarioDAO.funcionario.setMatricula(tfMatricula.getText());
            funcionarioDAO.funcionario.setNome(tfNome.getText());
            String dataEN = FormatDateEN(ftDataNascimento.getText());
            funcionarioDAO.funcionario.setDataNascimento(dataEN);
            if (rbMasc.isSelected()) {
                funcionarioDAO.funcionario.setSexo("M");
            } else if (rbFem.isSelected()) {
                funcionarioDAO.funcionario.setSexo("F");
            }
            funcionarioDAO.funcionario.setTelefone(tfTelefone.getText());
            funcionarioDAO.funcionario.setCelular(tfCelular.getText());
            funcionarioDAO.funcionario.setCpf(ftCpf.getText());
            funcionarioDAO.funcionario.setRg(ftRg.getText());
            funcionarioDAO.funcionario.setCep(ftCep.getText());
            funcionarioDAO.funcionario.setEndereco(tfEndereco.getText());
            funcionarioDAO.funcionario.setBairro(tfBairro.getText());
            funcionarioDAO.funcionario.setCidade(tfCidade.getText());
            String dataEN2 = FormatDateEN(ftDataAdmissao.getText());
            funcionarioDAO.funcionario.setDataAdmissao(dataEN2);
            funcionarioDAO.funcionario.setCarteiraTrabalho(tfCarteiraTrabalho.getText());
            funcionarioDAO.funcionario.setCargo(cbCargo.getSelectedItem().toString());
            funcionarioDAO.funcionario.setSalario(tfSalario.getText());
            funcionarioDAO.funcionario.setUsuario(tfUsuario.getText());
            funcionarioDAO.funcionario.setPerfil(cbPerfil.getSelectedItem().toString());
        } else {
            limpaCampos();
        }
    }

    public String FormatDateBR(String dataEN) {
        String dataBR = dataEN;
        dataBR = dataBR.substring(8, 10) + "/"
                + dataBR.substring(5, 7) + "/"
                + dataBR.substring(0, 4);
        return dataBR;
    }

    //Formantando do padrão 'BRASILEIRO' para o padrão 'AMERICANO'
    public String FormatDateEN(String dataBR) {
        String dataEN = dataBR;
        dataEN = dataEN.substring(6, 10) + "/"
                + dataEN.substring(3, 5) + "/"
                + dataEN.substring(0, 2);
        return dataEN;
    }

    public void HabilitaCampos(boolean cMatricula, boolean cNome, boolean DtNasc, boolean cSexo) {
        tfMatricula.setEnabled(cMatricula);
    }

    public String FormataV(String valorP) {
        String valorV = (tfSalario.getText().replace(",", ".").toString());
        return valorV;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btContratar;
    private javax.swing.JButton btDemitir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btListFunc;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbPerfil;
    private javax.swing.JFormattedTextField ftCep;
    private javax.swing.JFormattedTextField ftCpf;
    private javax.swing.JFormattedTextField ftDataAdmissao;
    private javax.swing.JFormattedTextField ftDataNascimento;
    private javax.swing.JTextField ftRg;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCarteiraTrabalho;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JFormattedTextField tfTelefone;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
