/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopecas;
import java.sql.SQLException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author nicol
 */
public class CadastroFornecedores extends javax.swing.JFrame {
    private FornecedorDAO fornecedorDAO;
    static void abrir() {
        CadastroFornecedores frame = new CadastroFornecedores();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* capturando o tamanho da tela onde está rodando este programa */
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((tela.width - frame.getSize().width)/2, 
                (tela.height - frame.getSize().height)/2);
        frame.setVisible(true);
    }

    /**
     * Creates new form CadastroFornecedores
     */
    public CadastroFornecedores() {
        initComponents();
        fornecedorDAO = new FornecedorDAO();
        setTitle("Sistema de Cadastro de Fornecedores- Elite Auto-Car");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        ftTelefone = new javax.swing.JFormattedTextField();
        ftCep = new javax.swing.JFormattedTextField();
        ftCnpj = new javax.swing.JFormattedTextField();
        btNovo = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFornecedores = new javax.swing.JTable();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Novo.jpg"))); // NOI18N
        jButton1.setText("Novo");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Contratar.jpg"))); // NOI18N
        jButton2.setText("Contratar");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Atualizar.jpg"))); // NOI18N
        jButton3.setText("Atualizar");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Demitir.jpg"))); // NOI18N
        jButton4.setText("Demitir");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Limpar.jpg"))); // NOI18N
        jButton5.setText("Limpar");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Sair.jpg"))); // NOI18N
        jButton6.setText("Sair");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 20)); // NOI18N
        jLabel1.setText("Cadastro de Fornecedores");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações do Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nome/ Razão Social");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Endereço");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cidade");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Estado");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CEP");

        cbEstado.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Telefone ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("CNPJ/CGC");

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Pesquisar.jpg"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        try {
            ftTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftCnpjActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 351, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ftCep)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btBuscar)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 105, Short.MAX_VALUE))))
                    .addComponent(tfEndereco))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(ftTelefone)
                    .addComponent(ftCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscar)
                            .addComponent(ftTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Novo.jpg"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btGravar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Gravar.jpg"))); // NOI18N
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Atualizar.jpg"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Excluir.jpg"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Limpar.jpg"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/voltar.jpg"))); // NOI18N
        btSair.setText("Voltar");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Fornecedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jtFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFornecedores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 6, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btSair))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        FormPrincipal.abrir();
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        FormPrincipal.abrir();
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        if(tfCodigo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Código.");
            tfCodigo.requestFocus();
            return;
        }
        if(tfNome.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Nome.");
            tfNome.requestFocus();
            return;
        }
        if(ftTelefone.getText().equals("(  )      -    "))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Telefone.");
            ftTelefone.requestFocus();
            return;
        }
        if(tfEndereco.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Endereco.");
            tfEndereco.requestFocus();
            return;
        }
        if(ftCnpj.getText().equals("  .   .   /    -  "))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo CNPJ.");
            ftCnpj.requestFocus();
            return;
        }
        if(tfCidade.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Cidade.");
            tfCidade.requestFocus();
            return;
        }
        if(cbEstado.getSelectedItem().equals("-"))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Estado.");
            cbEstado.requestFocus();
            return;
        }
        if(ftCep.getText().equals("  .   -   "))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo CEP.");
            ftCep.requestFocus();
            return;
        }
        fornecedorDAO.fornecedor.setCodigo(tfCodigo.getText());
        fornecedorDAO.fornecedor.setNome(tfNome.getText());
        fornecedorDAO.fornecedor.setTelefone(ftTelefone.getText());
        fornecedorDAO.fornecedor.setEndereco(tfEndereco.getText());
        fornecedorDAO.fornecedor.setCnpj(ftCnpj.getText());
        fornecedorDAO.fornecedor.setCidade(tfCidade.getText());
        fornecedorDAO.fornecedor.setEstado(""+cbEstado.getSelectedItem());
        fornecedorDAO.fornecedor.setCep(ftCep.getText());
        JOptionPane.showMessageDialog(null, fornecedorDAO.inserirFornecedor());
        limpaCampos();
    }//GEN-LAST:event_btGravarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        tfCodigo.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        if(tfCodigo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Código.");
            tfCodigo.requestFocus();
            return;
        }
        if(tfNome.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Nome.");
            tfNome.requestFocus();
            return;
        }
        if(ftTelefone.getText().equals("(  )      -    "))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Telefone.");
            ftTelefone.requestFocus();
            return;
        }
        if(tfEndereco.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Endereco.");
            tfEndereco.requestFocus();
            return;
        }
        if(ftCnpj.getText().equals("  .   .   /    -  "))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo CNPJ.");
            ftCnpj.requestFocus();
            return;
        }
        if(tfCidade.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Cidade.");
            tfCidade.requestFocus();
            return;
        }
        if(cbEstado.getSelectedItem().equals("-"))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo Estado.");
            cbEstado.requestFocus();
            return;
        }
        if(ftCep.getText().equals("  .   -   "))
        {
            JOptionPane.showMessageDialog(null,"Preencha o campo CEP.");
            ftCep.requestFocus();
            return;
        }
        fornecedorDAO.fornecedor.setCodigo(""+tfCodigo.getText());
        fornecedorDAO.fornecedor.setNome(""+tfNome.getText());
        fornecedorDAO.fornecedor.setTelefone(""+ftTelefone.getText());
        fornecedorDAO.fornecedor.setEndereco(""+tfEndereco.getText());
        fornecedorDAO.fornecedor.setCnpj(""+ftCnpj.getText());
        fornecedorDAO.fornecedor.setCidade(""+tfCidade.getText());
        fornecedorDAO.fornecedor.setEstado(""+cbEstado.getSelectedItem());
        fornecedorDAO.fornecedor.setCep(""+ftCep.getText());
        JOptionPane.showMessageDialog(null, fornecedorDAO.atualizarFornecedor());
        limpaCampos();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if(tfCodigo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Digite o código do funcionario a ser excluido.");
            tfCodigo.requestFocus();
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja Excluir?","ALERTA",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resposta==0)
        {
            fornecedorDAO.fornecedor.setCodigo("" + tfCodigo.getText());
            JOptionPane.showMessageDialog(null, fornecedorDAO.excluirFornecedor());
            limpaCampos();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Fornecedor não excluido.");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        if(!tfCodigo.getText().equals(""))
        {
            fornecedorDAO.fornecedor.setCodigo(tfCodigo.getText());
            if (fornecedorDAO.localizarFornecedor())             
            {
                tfCodigo.setText(fornecedorDAO.fornecedor.getCodigo());
                tfNome.setText(fornecedorDAO.fornecedor.getNome());
                ftTelefone.setText(fornecedorDAO.fornecedor.getTelefone());
                tfEndereco.setText(fornecedorDAO.fornecedor.getEndereco());
                ftCnpj.setText(fornecedorDAO.fornecedor.getCnpj());
                tfCidade.setText(fornecedorDAO.fornecedor.getCidade());
                cbEstado.setSelectedItem(fornecedorDAO.fornecedor.getEstado());
                ftCep.setText(fornecedorDAO.fornecedor.getCep());
            }
        }      
        else
        {
            JOptionPane.showMessageDialog(null, "Fornecedor não encontrado ou inexistente.");
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        String codigoNovo;
        codigoNovo = ""+fornecedorDAO.proximoFornecedor();
        if(!codigoNovo.equals("0"))
        {
            tfCodigo.setText(codigoNovo);
            tfNome.requestFocus();
            campoDesa(false);
        }
    }//GEN-LAST:event_btNovoActionPerformed

    private void ftCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftCnpjActionPerformed

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btBuscarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String sql = "select * from fornecedores";
        preencherTabela(sql);
    }//GEN-LAST:event_formWindowActivated

    private void jtFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFornecedoresMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jtFornecedores.getSelectedRow();
        if(linhaSelecionada >= 0)
        {
            tfCodigo.setText(jtFornecedores.getValueAt(linhaSelecionada, 0).toString());
            tfNome.setText(jtFornecedores.getValueAt(linhaSelecionada, 1).toString());
            ftTelefone.setText(jtFornecedores.getValueAt(linhaSelecionada, 2).toString());
            tfEndereco.setText(jtFornecedores.getValueAt(linhaSelecionada, 3).toString());
            ftCnpj.setText(jtFornecedores.getValueAt(linhaSelecionada, 4).toString());
            tfCidade.setText(jtFornecedores.getValueAt(linhaSelecionada, 5).toString());
            cbEstado.setSelectedItem(jtFornecedores.getValueAt(linhaSelecionada, 6).toString());
            ftCep.setText(jtFornecedores.getValueAt(linhaSelecionada, 7).toString());          
        }
    }//GEN-LAST:event_jtFornecedoresMouseClicked
    public void preencherTabela(String sql)
    {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"CÓDIGO","NOME","TELEFONE","ENDEREÇO","CNPJ","CIDADE","ESTADO","CEP"};
        fornecedorDAO.pesquisarFornecedor(sql);
        try
        {
            fornecedorDAO.resultSet.first();
            do
            {
                dados.add(new Object[]{
                    fornecedorDAO.resultSet.getInt("codigo"),
                    fornecedorDAO.resultSet.getString("nome"),
                    fornecedorDAO.resultSet.getString("telefone"),
                    fornecedorDAO.resultSet.getString("endereco"),
                    fornecedorDAO.resultSet.getString("cnpj"),
                    fornecedorDAO.resultSet.getString("cidade"),
                    fornecedorDAO.resultSet.getString("estado"),
                    fornecedorDAO.resultSet.getString("cep")});
            }
            while(fornecedorDAO.resultSet.next());
        } catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Erro: \n" + erro);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jtFornecedores.setModel(modelo);
        jtFornecedores.getColumnModel().getColumn(0).setPreferredWidth(60);
        jtFornecedores.getColumnModel().getColumn(0).setResizable(false);
        jtFornecedores.getColumnModel().getColumn(1).setPreferredWidth(200);
        jtFornecedores.getColumnModel().getColumn(1).setResizable(true);
        jtFornecedores.getColumnModel().getColumn(2).setPreferredWidth(120);
        jtFornecedores.getColumnModel().getColumn(2).setResizable(false);
        jtFornecedores.getColumnModel().getColumn(3).setPreferredWidth(130);
        jtFornecedores.getColumnModel().getColumn(3).setResizable(false);
        jtFornecedores.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtFornecedores.getColumnModel().getColumn(4).setResizable(false);
        jtFornecedores.getColumnModel().getColumn(5).setPreferredWidth(130);
        jtFornecedores.getColumnModel().getColumn(5).setResizable(false);
        jtFornecedores.getColumnModel().getColumn(6).setPreferredWidth(130);
        jtFornecedores.getColumnModel().getColumn(6).setResizable(false);
        jtFornecedores.getColumnModel().getColumn(7).setPreferredWidth(130);
        jtFornecedores.getColumnModel().getColumn(7).setResizable(false);
        jtFornecedores.getTableHeader().setReorderingAllowed(false);
        jtFornecedores.setAutoResizeMode(jtFornecedores.AUTO_RESIZE_OFF);
        jtFornecedores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        fornecedorDAO.conecta.fecharBD();
    }
    public void campoDesa(boolean cCgodio)
    {
        tfCodigo.setEnabled(cCgodio);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedores().setVisible(true);
            }
        });
    }
    public void limpaCampos()
    {
        tfCodigo.setText("");
        tfNome.setText("");
        ftTelefone.setText("");
        tfEndereco.setText("");
        ftCnpj.setText("");
        tfCidade.setText("");
        cbEstado.setSelectedItem("-");
        ftCep.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JFormattedTextField ftCep;
    private javax.swing.JFormattedTextField ftCnpj;
    private javax.swing.JFormattedTextField ftTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtFornecedores;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
