/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopecas;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Aluno Senac
 */
public class CadastroProduto extends javax.swing.JFrame {

    private ProdutoDAO produtoDAO;
    File arquivoFoto = null;
    String urlFoto; // url da foto
    int botaoFoto = 1; // variável que possibilita pegar e/ou eliminar foto através do mesmo botão
    BufferedImage imagemEscolhida;

    static void abrir() {
        CadastroProduto frame = new CadastroProduto();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* capturando o tamanho da tela onde está rodando este programa */
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((tela.width - frame.getSize().width) / 2,
                (tela.height - frame.getSize().height) / 2);
        frame.setVisible(true);
    }

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        produtoDAO = new ProdutoDAO();
        String sql = "select * from produto";
        preencherTabela(sql);
        setTitle("Sistema de Cadastro de Produto- Elite Auto-Car");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfPreco = new javax.swing.JTextField();
        tfQuantidade = new javax.swing.JTextField();
        cbFornecedor = new javax.swing.JComboBox();
        btBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbCarrosCompa = new javax.swing.JComboBox();
        cbMarca = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfCodigoFornecedor = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProduto = new javax.swing.JTable();
        btImagem = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 20)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações dos Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Preço:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Quantidade:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Marca:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Fornecedor:");

        tfQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantidadeActionPerformed(evt);
            }
        });

        cbFornecedor.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cbFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "COMANDO Auto Peças", "FATOR Distribuidora de Auto Peças", "DISAPE Distribuidora de Auto Peças", "DKP Distribuidora Auto Peças", " " }));

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Pesquisar.jpg"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Carros Compatíveis:");

        cbCarrosCompa.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cbCarrosCompa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Gol", "Fox", "Up", "Uno", "Siena", "Celta", "Classic", " ", " " }));

        cbMarca.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cbMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Volkswagen", "Fiat", "Chevrolet" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Código do Fornecedor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCarrosCompa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscar)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tfCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbCarrosCompa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagem do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Novo.jpg"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btGravar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Gravar.jpg"))); // NOI18N
        btGravar.setText("Salvar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Atualizar.jpg"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Excluir.jpg"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Limpar.jpg"))); // NOI18N
        btLimpar.setText("Limpar Campos");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/voltar.jpg"))); // NOI18N
        btSair.setText("Voltar");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTProduto);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );

        btImagem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Camera.jpg"))); // NOI18N
        btImagem.setText("Foto");
        btImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btNovo)
                                .addGap(18, 18, 18)
                                .addComponent(btGravar)
                                .addGap(18, 18, 18)
                                .addComponent(btAtualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(btImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImagem)
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        FormPrincipal.abrir();
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
        atualizaCampos();
        lbImagem.setIcon(null);
        lbImagem.setText("");
        BufferedImage bi;
        String sql = "select * from produto where codigo = " + tfCodigo.getText();
        produtoDAO.pesquisarProduto(sql);
        /* tentativa da pesquisa no banco de dados */
        try {
            produtoDAO.resultSet.first();
            urlFoto = produtoDAO.resultSet.getString("imagem");
            /* tentativa de colocar a imagem na tela */
            try {
                arquivoFoto = new File(urlFoto);
                //carrega a imagem real num buffer
                bi = ImageIO.read(arquivoFoto);
                //cria um buffer auxiliar com o tamanho desejado
                BufferedImage aux = new BufferedImage(165, 140, bi.getType());
                //pega a classe graphics do aux para edicao
                Graphics2D g = aux.createGraphics();
                //cria a transformacao
                AffineTransform at = AffineTransform.getScaleInstance((double) 165 / bi.getWidth(), (double) 140 / bi.getHeight());
                //pinta e transforma a imagem real no auxiliar
                g.drawRenderedImage(bi, at);
                //seta no jlabel
                lbImagem.setIcon(new ImageIcon(aux));
                lbImagem.setText(null);
                imagemEscolhida = aux;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Imagem não encontrada no arquivo .");
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Imagem não encontrada no banco.");
        }
        produtoDAO.produto.setCodigo(tfCodigo.getText());
        produtoDAO.produto.setNome(tfNome.getText());
        produtoDAO.produto.setCarrosCompativeis(cbCarrosCompa.getSelectedItem().toString());
        produtoDAO.produto.setFornecedor(cbFornecedor.getSelectedItem().toString());
        produtoDAO.produto.setMarca(cbMarca.getSelectedItem().toString());
        produtoDAO.produto.setImagem(urlFoto);
        produtoDAO.produto.setCodigoFornecedor(tfCodigoFornecedor.getText());
        String valorV = FormataV(tfPreco.getText());
        produtoDAO.produto.setPreco(valorV);


    }//GEN-LAST:event_btBuscarActionPerformed

    private void tfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        String codigoNovo;
        codigoNovo = "" + produtoDAO.proximoCodProduto();
        limpaCampos();
        if (!codigoNovo.equals("0")) {
            tfCodigo.setText(codigoNovo);
            tfNome.requestFocus();
            campoDesa(false);

//            capturarImagemPadrao();
        }
    }//GEN-LAST:event_btNovoActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        // TODO add your handling code here:
        if (tfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código.");
            tfCodigo.requestFocus();
            return;
        }
        if (tfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome.");
            tfNome.requestFocus();
            return;
        }
        if (cbCarrosCompa.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um Carro Compatível.");
            cbCarrosCompa.requestFocus();
            return;
        }
        if (cbFornecedor.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um Fornecedor.");
            cbFornecedor.requestFocus();
            return;
        }
        if (cbMarca.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione uma Marca.");
            cbMarca.requestFocus();
            return;
        }
        if (tfQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Quantidade.");
            tfQuantidade.requestFocus();
            return;
        }
        if (tfPreco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Preço.");
            tfPreco.requestFocus();
            return;
        }
        if (lbImagem.getIcon() == null) {
            JOptionPane.showMessageDialog(null, "Escolha uma imagem.");
            btImagem.requestFocus();
            return;
        }
        /* Preenchendo os atributos do objeto filme (instanciado da Classe Filmes) */
        produtoDAO.produto.setCodigo(tfCodigo.getText());
        produtoDAO.produto.setNome(tfNome.getText());
        produtoDAO.produto.setCarrosCompativeis(cbCarrosCompa.getSelectedItem().toString());
        produtoDAO.produto.setFornecedor(cbFornecedor.getSelectedItem().toString());
        produtoDAO.produto.setMarca(cbMarca.getSelectedItem().toString());
        produtoDAO.produto.setQuantidade(tfQuantidade.getText());
        String valorV = FormataV(tfPreco.getText());
        produtoDAO.produto.setPreco(valorV);
        produtoDAO.produto.setImagem(String.valueOf(arquivoFoto));
        produtoDAO.produto.setCodigoFornecedor(tfCodigoFornecedor.getText());
        JOptionPane.showMessageDialog(null, produtoDAO.inserirProduto());
        limpaCampos();
        String sql = "select * from produto";
        preencherTabela(sql);

    }//GEN-LAST:event_btGravarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
        if (tfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Código.");
            tfCodigo.requestFocus();
            return;
        }
        if (tfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Nome.");
            tfNome.requestFocus();
            return;
        }
        if (cbCarrosCompa.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um Carro Compatível.");
            cbCarrosCompa.requestFocus();
            return;
        }
        if (cbFornecedor.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione um Fornecedor.");
            cbFornecedor.requestFocus();
            return;
        }
        if (cbMarca.getSelectedItem().equals("Selecione")) {
            JOptionPane.showMessageDialog(null, "Selecione uma Marca.");
            cbMarca.requestFocus();
            return;
        }
        if (tfQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Quantidade.");
            tfQuantidade.requestFocus();
            return;
        }
        if (tfPreco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Preço.");
            tfPreco.requestFocus();
            return;
        }

        produtoDAO.produto.setCodigo(tfCodigo.getText());
        produtoDAO.produto.setNome(tfNome.getText());
        produtoDAO.produto.setCarrosCompativeis(cbCarrosCompa.getSelectedItem().toString());
        produtoDAO.produto.setFornecedor(cbFornecedor.getSelectedItem().toString());
        produtoDAO.produto.setMarca(cbMarca.getSelectedItem().toString());
        produtoDAO.produto.setQuantidade(tfQuantidade.getText());
        String valorP = FormataV(tfPreco.getText());
        produtoDAO.produto.setPreco(valorP);
        produtoDAO.produto.setImagem(String.valueOf(arquivoFoto));
        produtoDAO.produto.setCodigoFornecedor(tfCodigoFornecedor.getText());
        JOptionPane.showMessageDialog(null, produtoDAO.atualizarProduto());
        limpaCampos();
        String sql = "select * from produto";
        preencherTabela(sql);
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (resposta == 0) {
            if (tfCodigo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha o campo Código.");
                tfCodigo.requestFocus();
                return;
            }
            /* Preenchendo os atributos do objeto filme (instanciado da Classe Filmes) */
            produtoDAO.produto.setCodigo(tfCodigo.getText());
            JOptionPane.showMessageDialog(null, produtoDAO.excluirProduto());
            limpaCampos();
            String sql = "select * from produto";
            preencherTabela(sql);

        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImagemActionPerformed
        // TODO add your handling code here:
        capturarImagem();
    }//GEN-LAST:event_btImagemActionPerformed

    private void jTProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutoMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jTProduto.getSelectedRow();
        if (linhaSelecionada >= 0) {

            tfCodigo.setText(jTProduto.getValueAt(linhaSelecionada, 0).toString());
            tfNome.setText(jTProduto.getValueAt(linhaSelecionada, 1).toString());
            cbCarrosCompa.setSelectedItem(jTProduto.getValueAt(linhaSelecionada, 2).toString());
            cbFornecedor.setSelectedItem(jTProduto.getValueAt(linhaSelecionada, 3).toString());
            cbMarca.setSelectedItem(jTProduto.getValueAt(linhaSelecionada, 4).toString());
            tfQuantidade.setText(jTProduto.getValueAt(linhaSelecionada, 5).toString());
            tfPreco.setText(jTProduto.getValueAt(linhaSelecionada, 6).toString());
            tfCodigoFornecedor.setText(jTProduto.getValueAt(linhaSelecionada, 7).toString());
            lbImagem.setIcon(null);
            lbImagem.setText("");
            BufferedImage bi;
            String sql = "select * from produto where codigo = " + tfCodigo.getText();
            produtoDAO.pesquisarProduto(sql);
            /* tentativa da pesquisa no banco de dados */
            try {
                produtoDAO.resultSet.first();
                urlFoto = produtoDAO.resultSet.getString("imagem");
                /* tentativa de colocar a imagem na tela */
                try {
                    arquivoFoto = new File(urlFoto);
                    //carrega a imagem real num buffer
                    bi = ImageIO.read(arquivoFoto);
                    //cria um buffer auxiliar com o tamanho desejado
                    BufferedImage aux = new BufferedImage(165, 140, bi.getType());
                    //pega a classe graphics do aux para edicao
                    Graphics2D g = aux.createGraphics();
                    //cria a transformacao
                    AffineTransform at = AffineTransform.getScaleInstance((double) 165 / bi.getWidth(), (double) 140 / bi.getHeight());
                    //pinta e transforma a imagem real no auxiliar
                    g.drawRenderedImage(bi, at);
                    //seta no jlabel
                    lbImagem.setIcon(new ImageIcon(aux));
                    lbImagem.setText(null);
                    imagemEscolhida = aux;
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Imagem não encontrada no arquivo .");
                }
            } catch (SQLException erro) {
                JOptionPane.showMessageDialog(null, "Imagem não encontrada no banco.");
            }

            produtoDAO.produto.setCodigo(tfCodigo.getText());
            produtoDAO.produto.setNome(tfNome.getText());
            produtoDAO.produto.setCarrosCompativeis(cbCarrosCompa.getSelectedItem().toString());
            produtoDAO.produto.setFornecedor(cbFornecedor.getSelectedItem().toString());
            produtoDAO.produto.setMarca(cbMarca.getSelectedItem().toString());
            produtoDAO.produto.setImagem(urlFoto);

        }
    }//GEN-LAST:event_jTProdutoMouseClicked

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        limpaCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    /*private void capturarImagemPadrao() {
        BufferedImage bi;
        try {
            urlFoto = "C:\\Users\\LG\\Documents\\NetBeansProjects\\AutoPecas\\src\\Imagens\\ftPadrao";
            arquivoFoto = new File(urlFoto);
            //carrega a imagem real num buffer
            bi = ImageIO.read(arquivoFoto);
            //cria um buffer auxiliar com o tamanho desejado
            BufferedImage aux = new BufferedImage(165, 140, bi.getType());
            //pega a classe graphics do aux para edicao
            Graphics2D g = aux.createGraphics();
            //cria a transformacao
            AffineTransform at = AffineTransform.getScaleInstance((double) 165 / bi.getWidth(), (double) 140 / bi.getHeight());
            //pinta e transforma a imagem real no auxiliar
            g.drawRenderedImage(bi, at);
            //seta no jlabel
            lbImagem.setIcon(new ImageIcon(aux));
            lbImagem.setText(null);
            imagemEscolhida = aux;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Imagem não encontrada.");
        }
    }*/
    private void capturarImagem() {
        try {
            //Cria o objeto do tipo Janela JFileChooser
            JFileChooser fileChooser = new JFileChooser();
            //Define o título do JFileChooser
            fileChooser.setDialogTitle("Escolha a Imagem");
            //Define que só serão abertos arquivos
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                try {
                    //arquivo
                    arquivoFoto = fileChooser.getSelectedFile();
                    //carrega a imagem real num buffer
                    BufferedImage bi = ImageIO.read(arquivoFoto);
                    //cria um buffer auxiliar com o tamanho desejado
                    BufferedImage aux = new BufferedImage(165, 140, bi.getType());
                    //pega a classe graphics do aux para edicao
                    Graphics2D g = aux.createGraphics();
                    //cria a transformacao
                    AffineTransform at = AffineTransform.getScaleInstance((double) 165 / bi.getWidth(), (double) 140 / bi.getHeight());
                    //pinta e transforma a imagem real no auxiliar
                    g.drawRenderedImage(bi, at);
                    //seta no jlabel
                    lbImagem.setIcon(new ImageIcon(aux));
                    lbImagem.setText(null);
                    imagemEscolhida = aux;
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Arquivo não encontrado" + ex.toString());
                }
            } else {
//                capturarImagemPadrao();
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não conseguiu carregar a imagem.");
        }
        
    }
    public void campoDesa(boolean cCodigo){
            tfCodigo.setEnabled(cCodigo);
        }
    public void limpaCampos() {
        tfCodigo.setText("");
        tfNome.setText("");
        cbCarrosCompa.setSelectedItem("Selecione");
        cbFornecedor.setSelectedItem("Selecione");
        cbMarca.setSelectedItem("Selecione");
        tfQuantidade.setText("");
        tfPreco.setText("");
        lbImagem.setIcon(null);
        lbImagem.setText("");
        tfCodigo.requestFocus();
        tfCodigoFornecedor.setText("");
    }

    public void atualizaCampos() {
        produtoDAO.produto.setCodigo(tfCodigo.getText());
        if (produtoDAO.localizarProduto()) {
            tfCodigo.setText(produtoDAO.produto.getCodigo());
            tfNome.setText(produtoDAO.produto.getNome());
            cbCarrosCompa.setSelectedItem(produtoDAO.produto.getCarrosCompativeis());
            cbFornecedor.setSelectedItem(produtoDAO.produto.getFornecedor());
            cbMarca.setSelectedItem(produtoDAO.produto.getMarca());
            tfQuantidade.setText(produtoDAO.produto.getQuantidade());
            tfPreco.setText(produtoDAO.produto.getPreco());

        } else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado.");
            limpaCampos();
        }
    }

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Código", "Nome do Produto", "Carros Compatíveis", "Fornecedor", "Marca", "Quantidade", "Preço", "Código do Fornecedor"};
        produtoDAO.pesquisarProduto(sql);
        try {
            produtoDAO.resultSet.first();
            do {

                /* adicionando os dados que vem do banco para a tabela */
                String FormataT = FormataTabela(produtoDAO.resultSet.getString("preco"));
                dados.add(new Object[]{
                    produtoDAO.resultSet.getInt("codigo"),
                    produtoDAO.resultSet.getString("nome"),
                    produtoDAO.resultSet.getString("carrosCompativeis"),
                    produtoDAO.resultSet.getString("fornecedor"),
                    produtoDAO.resultSet.getString("marca"),
                    produtoDAO.resultSet.getString("quantidade"),
                    FormataT,
                    produtoDAO.resultSet.getString("fornecedores_codigo"),});
            } while (produtoDAO.resultSet.next());
        } catch (SQLException erro) {
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTProduto.setModel(modelo);
        jTProduto.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTProduto.getColumnModel().getColumn(0).setResizable(false);
        jTProduto.getColumnModel().getColumn(1).setPreferredWidth(220);  // define o tamanho das colunas e se será redimensionado ou não
        jTProduto.getColumnModel().getColumn(1).setResizable(true);  // não permite alterar o tamanho da coluna
        jTProduto.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTProduto.getColumnModel().getColumn(2).setResizable(false);
        jTProduto.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTProduto.getColumnModel().getColumn(3).setResizable(true);
        jTProduto.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTProduto.getColumnModel().getColumn(4).setResizable(false);
        jTProduto.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTProduto.getColumnModel().getColumn(5).setResizable(false);
        jTProduto.getColumnModel().getColumn(6).setPreferredWidth(150);
        jTProduto.getColumnModel().getColumn(6).setResizable(false);
        jTProduto.getColumnModel().getColumn(7).setPreferredWidth(150);
        jTProduto.getColumnModel().getColumn(7).setResizable(false);
        jTProduto.getTableHeader().setReorderingAllowed(false);  // Não permite reordenar as colunas
        jTProduto.setAutoResizeMode(jTProduto.AUTO_RESIZE_OFF); // Não permite redimensionar a tabela
        jTProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela
        produtoDAO.conecta.fecharBD();
    }
    public String FormataV(String valorP) {
        String valorV = (tfPreco.getText().replace(",", ".").toString());
        return valorV;
    }
    public String FormataTabela(String valorP)
    {
        String valorV = valorP.replace(".",",");
        return valorV;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btImagem;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox cbCarrosCompa;
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JComboBox cbMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTProduto;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfCodigoFornecedor;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
