/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopecas;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Aluno Senac
 */
public class TabelaListaFuncio extends javax.swing.JFrame {

    private FuncionarioDAO funcionarioDAO;

    static void abrir() {
        TabelaListaFuncio frame = new TabelaListaFuncio();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* capturando o tamanho da tela onde está rodando este programa */
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setLocation((tela.width - frame.getSize().width) / 2,
                (tela.height - frame.getSize().height) / 2);
        frame.setVisible(true);
    }

    public TabelaListaFuncio() {
        initComponents();
        funcionarioDAO = new FuncionarioDAO();
        setTitle("Tabela de Funcionários - Elite Auto Car");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btDemitir = new javax.swing.JButton();
        tfMatricula = new javax.swing.JTextField();
        tfPesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFuncionario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/voltar.jpg"))); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btDemitir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btDemitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Demitir.jpg"))); // NOI18N
        btDemitir.setText("Demitir");
        btDemitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDemitirActionPerformed(evt);
            }
        });

        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Pesquisar.jpg"))); // NOI18N
        btPesquisar.setText("Buscar Funcionário");
        btPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btPesquisarMouseClicked(evt);
            }
        });
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopecasImg/Cancelar.jpg"))); // NOI18N
        btCancelar.setText("Cancelar Busca");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Funcionários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTFuncionario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDemitir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231)
                        .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancelar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDemitir)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        String sql = "select * from funcionario";
        preencherTabela(sql);
        setCampos(false);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CadastroFuncionario.abrir();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btDemitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDemitirActionPerformed
        // TODO add your handling code here:
        if (tfMatricula.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo Matrícula.");
            tfMatricula.requestFocus();;
            return;
        }
        // Função OK_CANCEL_OPTION  para colocar um janela com opções "SIM" para excuir e "NÂO" para não exlcuir
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja Excluir este Funcionario ?", "", JOptionPane.OK_CANCEL_OPTION);
        if (resposta == 0) {
            funcionarioDAO.funcionario.setMatricula(tfMatricula.getText());
            funcionarioDAO.excluiOS();
            JOptionPane.showMessageDialog(null, funcionarioDAO.excluiFuncionario());
            limpaCampos();
            String sql = "select * from funcionario";
            //preecherTabela(sql);

        }
    }//GEN-LAST:event_btDemitirActionPerformed

    private void jTFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFuncionarioMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jTFuncionario.getSelectedRow();
        if (linhaSelecionada >= 0) {
            tfMatricula.setText(jTFuncionario.getValueAt(linhaSelecionada, 0).toString());
        }
    }//GEN-LAST:event_jTFuncionarioMouseClicked

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        if (tfPesquisa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Insira a Matrícula do Funcionário");
            requestFocus();
        } else {
            String sql = "select * from funcionario where matricula = " + tfPesquisa.getText();
            preencherTabela(sql);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPesquisarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisarMouseClicked

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        String sql = "select * from funcionario";
        preencherTabela(sql);
        tfPesquisa.setText("");
        tfMatricula.setText("");
    }//GEN-LAST:event_btCancelarActionPerformed

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Matricula", "Nome funcionario", "Data Nascimento", "Sexo", "Telefone", "Celular", "CPF", "RG", "Cep", "Endereco", "Bairro", "Cidade", "Data de Admissão", "Carteira de Trabalho", "Cargo", "Salário", "Perfil"};
        funcionarioDAO.pesquisarFuncionarios(sql);
        try {
            funcionarioDAO.resultSet.first();

            do {
                String dataBR = FormatDateBR(funcionarioDAO.resultSet.getString("dataNascimento"));
                String dataBR2 = FormatDateBR(funcionarioDAO.resultSet.getString("dataAdmissao"));
                String valorP = FormataTabela(funcionarioDAO.resultSet.getString("salario"));
                dados.add(new Object[]{funcionarioDAO.resultSet.getInt("matricula"), funcionarioDAO.resultSet.getString("nome"),
                    dataBR, funcionarioDAO.resultSet.getString("sexo"), funcionarioDAO.resultSet.getString("telefone"),
                    funcionarioDAO.resultSet.getString("celular"),
                    funcionarioDAO.resultSet.getString("cpf"), funcionarioDAO.resultSet.getString("rg"), funcionarioDAO.resultSet.getString("cep"), funcionarioDAO.resultSet.getString("endereco"), funcionarioDAO.resultSet.getString("bairro"), funcionarioDAO.resultSet.getString("cidade"),
                    dataBR2, funcionarioDAO.resultSet.getString("carteiraTrabalho"), funcionarioDAO.resultSet.getString("cargo"), valorP, funcionarioDAO.resultSet.getString("perfil")});
            } while (funcionarioDAO.resultSet.next());
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro: \n" + erro);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        jTFuncionario.setModel(modelo);
        jTFuncionario.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTFuncionario.getColumnModel().getColumn(0).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(1).setPreferredWidth(220); // define o tamanho das colunas e se será redimensionado
        jTFuncionario.getColumnModel().getColumn(1).setResizable(false);// não permite alterar o tamanho da coluna
        jTFuncionario.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTFuncionario.getColumnModel().getColumn(2).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(3).setResizable(true);
        jTFuncionario.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(4).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(5).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(6).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(6).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(7).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(7).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(8).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(8).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(9).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(9).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(10).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(10).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(11).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(11).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(12).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(12).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(13).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(13).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(14).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(14).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(15).setPreferredWidth(150);
        jTFuncionario.getColumnModel().getColumn(15).setResizable(false);
        jTFuncionario.getColumnModel().getColumn(15).setPreferredWidth(60);
        jTFuncionario.getColumnModel().getColumn(15).setResizable(false);
        jTFuncionario.getTableHeader().setReorderingAllowed(false);  //não permite reordenar as colunas
        jTFuncionario.setAutoResizeMode(jTFuncionario.AUTO_RESIZE_OFF); // não permite redimensionar a tabela
        jTFuncionario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // permite selecionar apenas 1 elemento da tabela
        funcionarioDAO.conecta.fecharBD();
    }

    public String FormatDateBR(String dataEN) {
        String dataBR = dataEN;
        dataBR = dataBR.substring(8, 10) + "/"
                + dataBR.substring(5, 7) + "/"
                + dataBR.substring(0, 4);
        return dataBR;
    }

    //Formantando do padrão 'BRASILEIRO' para o padrão 'AMERICANO'
    public String FormatDateEN(String dataBR) {
        String dataEN = dataBR;
        dataEN = dataEN.substring(6, 10) + "/"
                + dataEN.substring(3, 5) + "/"
                + dataEN.substring(0, 2);
        return dataEN;
    }

    public String FormataTabela(String valorP) {
        String valorV = valorP.replace(".", ",");
        return valorV;
    }

    /**
     * @param args the command line arguments
     */
    public void limpaCampos() {
        tfMatricula.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaListaFuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaListaFuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaListaFuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaListaFuncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaListaFuncio().setVisible(true);
            }
        });
    }

    public void setCampos(boolean tMatricula) {
        tfMatricula.setEnabled(tMatricula);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btDemitir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTFuncionario;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
